/*
Copyright 2022 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"

// GetCondition of this CertBasedOIDCLogin.
func (mg *CertBasedOIDCLogin) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this CertBasedOIDCLogin.
func (mg *CertBasedOIDCLogin) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this CertBasedOIDCLogin.
func (mg *CertBasedOIDCLogin) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this CertBasedOIDCLogin.
func (mg *CertBasedOIDCLogin) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return &xpv1.ProviderConfigReference{Name: mg.Spec.ProviderConfigReference.Name}
}


// GetWriteConnectionSecretToReference of this CertBasedOIDCLogin.
func (mg *CertBasedOIDCLogin) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this CertBasedOIDCLogin.
func (mg *CertBasedOIDCLogin) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this CertBasedOIDCLogin.
func (mg *CertBasedOIDCLogin) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this CertBasedOIDCLogin.
func (mg *CertBasedOIDCLogin) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this CertBasedOIDCLogin.
func (mg *CertBasedOIDCLogin) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.Reference{Name: r.Name}
}


// SetWriteConnectionSecretToReference of this CertBasedOIDCLogin.
func (mg *CertBasedOIDCLogin) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}

// GetCondition of this KubeConfigGenerator.
func (mg *KubeConfigGenerator) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this KubeConfigGenerator.
func (mg *KubeConfigGenerator) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this KubeConfigGenerator.
func (mg *KubeConfigGenerator) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this KubeConfigGenerator.
func (mg *KubeConfigGenerator) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return &xpv1.ProviderConfigReference{Name: mg.Spec.ProviderConfigReference.Name}
}


// GetWriteConnectionSecretToReference of this KubeConfigGenerator.
func (mg *KubeConfigGenerator) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this KubeConfigGenerator.
func (mg *KubeConfigGenerator) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this KubeConfigGenerator.
func (mg *KubeConfigGenerator) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this KubeConfigGenerator.
func (mg *KubeConfigGenerator) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this KubeConfigGenerator.
func (mg *KubeConfigGenerator) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.Reference{Name: r.Name}
}


// SetWriteConnectionSecretToReference of this KubeConfigGenerator.
func (mg *KubeConfigGenerator) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}
