/*
Copyright 2022 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"

// GetCondition of this CloudManagement.
func (mg *CloudManagement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this CloudManagement.
func (mg *CloudManagement) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this CloudManagement.
func (mg *CloudManagement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this CloudManagement.
func (mg *CloudManagement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this CloudManagement.
func (mg *CloudManagement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this CloudManagement.
func (mg *CloudManagement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this CloudManagement.
func (mg *CloudManagement) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this CloudManagement.
func (mg *CloudManagement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this CloudManagement.
func (mg *CloudManagement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.ProviderConfigReference{Name: r.Name, Kind: r.Kind}
}

// SetWriteConnectionSecretToReference of this CloudManagement.
func (mg *CloudManagement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}

// GetCondition of this Directory.
func (mg *Directory) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this Directory.
func (mg *Directory) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this Directory.
func (mg *Directory) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this Directory.
func (mg *Directory) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this Directory.
func (mg *Directory) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this Directory.
func (mg *Directory) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this Directory.
func (mg *Directory) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this Directory.
func (mg *Directory) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this Directory.
func (mg *Directory) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.ProviderConfigReference{Name: r.Name, Kind: r.Kind}
}

// SetWriteConnectionSecretToReference of this Directory.
func (mg *Directory) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}

// GetCondition of this DirectoryEntitlement.
func (mg *DirectoryEntitlement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this DirectoryEntitlement.
func (mg *DirectoryEntitlement) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this DirectoryEntitlement.
func (mg *DirectoryEntitlement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this DirectoryEntitlement.
func (mg *DirectoryEntitlement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this DirectoryEntitlement.
func (mg *DirectoryEntitlement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this DirectoryEntitlement.
func (mg *DirectoryEntitlement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this DirectoryEntitlement.
func (mg *DirectoryEntitlement) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this DirectoryEntitlement.
func (mg *DirectoryEntitlement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this DirectoryEntitlement.
func (mg *DirectoryEntitlement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.ProviderConfigReference{Name: r.Name, Kind: r.Kind}
}

// SetWriteConnectionSecretToReference of this DirectoryEntitlement.
func (mg *DirectoryEntitlement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}

// GetCondition of this Entitlement.
func (mg *Entitlement) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this Entitlement.
func (mg *Entitlement) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this Entitlement.
func (mg *Entitlement) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this Entitlement.
func (mg *Entitlement) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this Entitlement.
func (mg *Entitlement) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this Entitlement.
func (mg *Entitlement) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this Entitlement.
func (mg *Entitlement) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this Entitlement.
func (mg *Entitlement) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this Entitlement.
func (mg *Entitlement) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.ProviderConfigReference{Name: r.Name, Kind: r.Kind}
}

// SetWriteConnectionSecretToReference of this Entitlement.
func (mg *Entitlement) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}

// GetCondition of this GlobalAccount.
func (mg *GlobalAccount) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this GlobalAccount.
func (mg *GlobalAccount) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this GlobalAccount.
func (mg *GlobalAccount) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this GlobalAccount.
func (mg *GlobalAccount) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this GlobalAccount.
func (mg *GlobalAccount) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this GlobalAccount.
func (mg *GlobalAccount) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this GlobalAccount.
func (mg *GlobalAccount) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this GlobalAccount.
func (mg *GlobalAccount) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this GlobalAccount.
func (mg *GlobalAccount) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.ProviderConfigReference{Name: r.Name, Kind: r.Kind}
}

// SetWriteConnectionSecretToReference of this GlobalAccount.
func (mg *GlobalAccount) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}

// GetCondition of this ServiceBinding.
func (mg *ServiceBinding) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this ServiceBinding.
func (mg *ServiceBinding) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this ServiceBinding.
func (mg *ServiceBinding) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ServiceBinding.
func (mg *ServiceBinding) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ServiceBinding.
func (mg *ServiceBinding) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this ServiceBinding.
func (mg *ServiceBinding) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this ServiceBinding.
func (mg *ServiceBinding) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this ServiceBinding.
func (mg *ServiceBinding) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ServiceBinding.
func (mg *ServiceBinding) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.ProviderConfigReference{Name: r.Name, Kind: r.Kind}
}

// SetWriteConnectionSecretToReference of this ServiceBinding.
func (mg *ServiceBinding) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}

// GetCondition of this ServiceInstance.
func (mg *ServiceInstance) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this ServiceInstance.
func (mg *ServiceInstance) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this ServiceInstance.
func (mg *ServiceInstance) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ServiceInstance.
func (mg *ServiceInstance) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ServiceInstance.
func (mg *ServiceInstance) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this ServiceInstance.
func (mg *ServiceInstance) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this ServiceInstance.
func (mg *ServiceInstance) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this ServiceInstance.
func (mg *ServiceInstance) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ServiceInstance.
func (mg *ServiceInstance) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.ProviderConfigReference{Name: r.Name, Kind: r.Kind}
}

// SetWriteConnectionSecretToReference of this ServiceInstance.
func (mg *ServiceInstance) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}

// GetCondition of this ServiceManager.
func (mg *ServiceManager) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this ServiceManager.
func (mg *ServiceManager) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this ServiceManager.
func (mg *ServiceManager) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ServiceManager.
func (mg *ServiceManager) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ServiceManager.
func (mg *ServiceManager) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this ServiceManager.
func (mg *ServiceManager) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this ServiceManager.
func (mg *ServiceManager) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this ServiceManager.
func (mg *ServiceManager) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ServiceManager.
func (mg *ServiceManager) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.ProviderConfigReference{Name: r.Name, Kind: r.Kind}
}

// SetWriteConnectionSecretToReference of this ServiceManager.
func (mg *ServiceManager) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}

// GetCondition of this Subaccount.
func (mg *Subaccount) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this Subaccount.
func (mg *Subaccount) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this Subaccount.
func (mg *Subaccount) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this Subaccount.
func (mg *Subaccount) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this Subaccount.
func (mg *Subaccount) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this Subaccount.
func (mg *Subaccount) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this Subaccount.
func (mg *Subaccount) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this Subaccount.
func (mg *Subaccount) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this Subaccount.
func (mg *Subaccount) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.ProviderConfigReference{Name: r.Name, Kind: r.Kind}
}

// SetWriteConnectionSecretToReference of this Subaccount.
func (mg *Subaccount) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}

// GetCondition of this SubaccountServiceBinding.
func (mg *SubaccountServiceBinding) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SubaccountServiceBinding.
func (mg *SubaccountServiceBinding) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SubaccountServiceBinding.
func (mg *SubaccountServiceBinding) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SubaccountServiceBinding.
func (mg *SubaccountServiceBinding) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SubaccountServiceBinding.
func (mg *SubaccountServiceBinding) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this SubaccountServiceBinding.
func (mg *SubaccountServiceBinding) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SubaccountServiceBinding.
func (mg *SubaccountServiceBinding) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SubaccountServiceBinding.
func (mg *SubaccountServiceBinding) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SubaccountServiceBinding.
func (mg *SubaccountServiceBinding) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.ProviderConfigReference{Name: r.Name, Kind: r.Kind}
}

// SetWriteConnectionSecretToReference of this SubaccountServiceBinding.
func (mg *SubaccountServiceBinding) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}

// GetCondition of this SubaccountServiceBroker.
func (mg *SubaccountServiceBroker) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SubaccountServiceBroker.
func (mg *SubaccountServiceBroker) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SubaccountServiceBroker.
func (mg *SubaccountServiceBroker) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SubaccountServiceBroker.
func (mg *SubaccountServiceBroker) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SubaccountServiceBroker.
func (mg *SubaccountServiceBroker) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this SubaccountServiceBroker.
func (mg *SubaccountServiceBroker) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SubaccountServiceBroker.
func (mg *SubaccountServiceBroker) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SubaccountServiceBroker.
func (mg *SubaccountServiceBroker) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SubaccountServiceBroker.
func (mg *SubaccountServiceBroker) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.ProviderConfigReference{Name: r.Name, Kind: r.Kind}
}

// SetWriteConnectionSecretToReference of this SubaccountServiceBroker.
func (mg *SubaccountServiceBroker) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}

// GetCondition of this SubaccountServiceInstance.
func (mg *SubaccountServiceInstance) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this SubaccountServiceInstance.
func (mg *SubaccountServiceInstance) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this SubaccountServiceInstance.
func (mg *SubaccountServiceInstance) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this SubaccountServiceInstance.
func (mg *SubaccountServiceInstance) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this SubaccountServiceInstance.
func (mg *SubaccountServiceInstance) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this SubaccountServiceInstance.
func (mg *SubaccountServiceInstance) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this SubaccountServiceInstance.
func (mg *SubaccountServiceInstance) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this SubaccountServiceInstance.
func (mg *SubaccountServiceInstance) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this SubaccountServiceInstance.
func (mg *SubaccountServiceInstance) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.ProviderConfigReference{Name: r.Name, Kind: r.Kind}
}

// SetWriteConnectionSecretToReference of this SubaccountServiceInstance.
func (mg *SubaccountServiceInstance) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}

// GetCondition of this Subscription.
func (mg *Subscription) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this Subscription.
func (mg *Subscription) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this Subscription.
func (mg *Subscription) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this Subscription.
func (mg *Subscription) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this Subscription.
func (mg *Subscription) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this Subscription.
func (mg *Subscription) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this Subscription.
func (mg *Subscription) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this Subscription.
func (mg *Subscription) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this Subscription.
func (mg *Subscription) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.ProviderConfigReference{Name: r.Name, Kind: r.Kind}
}

// SetWriteConnectionSecretToReference of this Subscription.
func (mg *Subscription) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}
