apiVersion: account.btp.sap.crossplane.io/v1alpha1
kind: ServiceBinding
metadata:
  name: destination-binding
  namespace: default
spec:
  forProvider:
    name: destination-binding
    # parameters: ... same options for setting parameters via json, yaml or secrets as for instances
    serviceInstanceRef:
      name: destination-instance
    subaccountRef:
      name: sa-serviceinstance
  # Optional: Enable rotation
  # rotation:
  #   ttl: 1440h
  #   frequency: 720h
  writeConnectionSecretToRef:
    name: destination-binding
