/*
Copyright 2022 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"

// GetCondition of this CloudFoundryEnvironment.
func (mg *CloudFoundryEnvironment) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this CloudFoundryEnvironment.
func (mg *CloudFoundryEnvironment) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this CloudFoundryEnvironment.
func (mg *CloudFoundryEnvironment) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this CloudFoundryEnvironment.
func (mg *CloudFoundryEnvironment) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return &xpv1.ProviderConfigReference{Name: mg.Spec.ProviderConfigReference.Name}
}


// GetWriteConnectionSecretToReference of this CloudFoundryEnvironment.
func (mg *CloudFoundryEnvironment) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this CloudFoundryEnvironment.
func (mg *CloudFoundryEnvironment) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this CloudFoundryEnvironment.
func (mg *CloudFoundryEnvironment) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this CloudFoundryEnvironment.
func (mg *CloudFoundryEnvironment) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this CloudFoundryEnvironment.
func (mg *CloudFoundryEnvironment) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.Reference{Name: r.Name}
}


// SetWriteConnectionSecretToReference of this CloudFoundryEnvironment.
func (mg *CloudFoundryEnvironment) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}

// GetCondition of this KymaEnvironment.
func (mg *KymaEnvironment) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this KymaEnvironment.
func (mg *KymaEnvironment) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this KymaEnvironment.
func (mg *KymaEnvironment) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this KymaEnvironment.
func (mg *KymaEnvironment) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return &xpv1.ProviderConfigReference{Name: mg.Spec.ProviderConfigReference.Name}
}


// GetWriteConnectionSecretToReference of this KymaEnvironment.
func (mg *KymaEnvironment) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this KymaEnvironment.
func (mg *KymaEnvironment) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this KymaEnvironment.
func (mg *KymaEnvironment) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this KymaEnvironment.
func (mg *KymaEnvironment) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this KymaEnvironment.
func (mg *KymaEnvironment) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.Reference{Name: r.Name}
}


// SetWriteConnectionSecretToReference of this KymaEnvironment.
func (mg *KymaEnvironment) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}

// GetCondition of this KymaEnvironmentBinding.
func (mg *KymaEnvironmentBinding) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this KymaEnvironmentBinding.
func (mg *KymaEnvironmentBinding) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this KymaEnvironmentBinding.
func (mg *KymaEnvironmentBinding) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this KymaEnvironmentBinding.
func (mg *KymaEnvironmentBinding) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return &xpv1.ProviderConfigReference{Name: mg.Spec.ProviderConfigReference.Name}
}


// GetWriteConnectionSecretToReference of this KymaEnvironmentBinding.
func (mg *KymaEnvironmentBinding) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this KymaEnvironmentBinding.
func (mg *KymaEnvironmentBinding) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this KymaEnvironmentBinding.
func (mg *KymaEnvironmentBinding) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this KymaEnvironmentBinding.
func (mg *KymaEnvironmentBinding) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this KymaEnvironmentBinding.
func (mg *KymaEnvironmentBinding) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.Reference{Name: r.Name}
}


// SetWriteConnectionSecretToReference of this KymaEnvironmentBinding.
func (mg *KymaEnvironmentBinding) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}

// GetCondition of this KymaModule.
func (mg *KymaModule) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this KymaModule.
func (mg *KymaModule) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this KymaModule.
func (mg *KymaModule) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this KymaModule.
func (mg *KymaModule) GetProviderConfigReference() *xpv1.ProviderConfigReference {
	if mg.Spec.ProviderConfigReference == nil {
		return nil
	}
	return &xpv1.ProviderConfigReference{Name: mg.Spec.ProviderConfigReference.Name}
}


// GetWriteConnectionSecretToReference of this KymaModule.
func (mg *KymaModule) GetWriteConnectionSecretToReference() *xpv1.LocalSecretReference {
	if mg.Spec.WriteConnectionSecretToReference == nil {
		return nil
	}
	return &xpv1.LocalSecretReference{Name: mg.Spec.WriteConnectionSecretToReference.Name}
}

// SetConditions of this KymaModule.
func (mg *KymaModule) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this KymaModule.
func (mg *KymaModule) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this KymaModule.
func (mg *KymaModule) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this KymaModule.
func (mg *KymaModule) SetProviderConfigReference(r *xpv1.ProviderConfigReference) {
	if r == nil {
		mg.Spec.ProviderConfigReference = nil
		return
	}
	mg.Spec.ProviderConfigReference = &xpv1.Reference{Name: r.Name}
}


// SetWriteConnectionSecretToReference of this KymaModule.
func (mg *KymaModule) SetWriteConnectionSecretToReference(r *xpv1.LocalSecretReference) {
	if r == nil {
		mg.Spec.WriteConnectionSecretToReference = nil
		return
	}
	mg.Spec.WriteConnectionSecretToReference = &xpv1.SecretReference{Name: r.Name}
}
