/*
Copyright 2022 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type SubaccountEnvironmentInstanceInitParameters struct {

	// (String) The type of the environment instance that is used.
	// The type of the environment instance that is used.
	EnvironmentType *string `json:"environmentType,omitempty" tf:"environment_type,omitempty"`

	// (String) The name of the landscape within the logged in region on which the environment instance is created.
	// The name of the landscape within the logged in region on which the environment instance is created.
	LandscapeLabel *string `json:"landscapeLabel,omitempty" tf:"landscape_label,omitempty"`

	// (String) The name of the environment instance.
	// The name of the environment instance.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The configuration parameters for the environment instance.
	// The configuration parameters for the environment instance.
	Parameters *string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (String) The name of the service plan for the environment instance in the corresponding service broker's catalog.
	// The name of the service plan for the environment instance in the corresponding service broker's catalog.
	PlanName *string `json:"planName,omitempty" tf:"plan_name,omitempty"`

	// (String) The name of the service for the environment instance in the corresponding service broker's catalog.
	// The name of the service for the environment instance in the corresponding service broker's catalog.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// (String) The ID of the subaccount.
	// The ID of the subaccount.
	// +crossplane:generate:reference:type=github.com/sap/crossplane-provider-btp/apis/account/v1alpha1.Subaccount
	// +crossplane:generate:reference:extractor=github.com/sap/crossplane-provider-btp/apis/account/v1alpha1.SubaccountUuid()
	// +crossplane:generate:reference:refFieldName=SubaccountRef
	// +crossplane:generate:reference:selectorFieldName=SubaccountSelector
	SubaccountID *string `json:"subaccountId,omitempty" tf:"subaccount_id,omitempty"`

	// Reference to a Subaccount in account to populate subaccountId.
	// +kubebuilder:validation:Optional
	SubaccountRef *v1.Reference `json:"subaccountRef,omitempty" tf:"-"`

	// Selector for a Subaccount in account to populate subaccountId.
	// +kubebuilder:validation:Optional
	SubaccountSelector *v1.Selector `json:"subaccountSelector,omitempty" tf:"-"`

	// (Attributes) (see below for nested schema)
	Timeouts *TimeoutsInitParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`
}

type SubaccountEnvironmentInstanceObservation struct {

	// (String) The ID of the associated environment broker.
	// The ID of the associated environment broker.
	BrokerID *string `json:"brokerId,omitempty" tf:"broker_id,omitempty"`

	// (String) The date and time when the resource was created in RFC3339 format.
	// The date and time when the resource was created in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) format.
	CreatedDate *string `json:"createdDate,omitempty" tf:"created_date,omitempty"`

	// (Map of Set of String) The set of words or phrases assigned to the environment instance.
	// The set of words or phrases assigned to the environment instance.
	CustomLabels map[string][]*string `json:"customLabels,omitempty" tf:"custom_labels,omitempty"`

	// based management user interface for the service instances.
	// The URL of the service dashboard, which is a web-based management user interface for the service instances.
	DashboardURL *string `json:"dashboardUrl,omitempty" tf:"dashboard_url,omitempty"`

	// (String) The description of the environment instance.
	// The description of the environment instance.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The type of the environment instance that is used.
	// The type of the environment instance that is used.
	EnvironmentType *string `json:"environmentType,omitempty" tf:"environment_type,omitempty"`

	// (String) The ID of the environment instance.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// specified key-value pairs that specify attributes of an environment instance.
	// The Broker-specified key-value pairs that specify attributes of an environment instance.
	Labels *string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the landscape within the logged in region on which the environment instance is created.
	// The name of the landscape within the logged in region on which the environment instance is created.
	LandscapeLabel *string `json:"landscapeLabel,omitempty" tf:"landscape_label,omitempty"`

	// (String) The date and time when the resource was last modified in RFC3339 format.
	// The date and time when the resource was last modified in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) format.
	LastModified *string `json:"lastModified,omitempty" tf:"last_modified,omitempty"`

	// (String) The name of the environment instance.
	// The name of the environment instance.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) An identifier that represents the last operation. This ID is returned by the environment brokers.
	// An identifier that represents the last operation. This ID is returned by the environment brokers.
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// (String) The configuration parameters for the environment instance.
	// The configuration parameters for the environment instance.
	Parameters *string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (String) The ID of the service plan for the environment instance in the corresponding service broker's catalog.
	// The ID of the service plan for the environment instance in the corresponding service broker's catalog.
	PlanID *string `json:"planId,omitempty" tf:"plan_id,omitempty"`

	// (String) The name of the service plan for the environment instance in the corresponding service broker's catalog.
	// The name of the service plan for the environment instance in the corresponding service broker's catalog.
	PlanName *string `json:"planName,omitempty" tf:"plan_name,omitempty"`

	// (String) The ID of the platform for the environment instance in the corresponding service broker's catalog.
	// The ID of the platform for the environment instance in the corresponding service broker's catalog.
	PlatformID *string `json:"platformId,omitempty" tf:"platform_id,omitempty"`

	// (String) The ID of the service for the environment instance in the corresponding service broker's catalog.
	// The ID of the service for the environment instance in the corresponding service broker's catalog.
	ServiceID *string `json:"serviceId,omitempty" tf:"service_id,omitempty"`

	// (String) The name of the service for the environment instance in the corresponding service broker's catalog.
	// The name of the service for the environment instance in the corresponding service broker's catalog.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// (String) The current state of the environment instance. Possible values are:
	// The current state of the environment instance. Possible values are:
	//
	// | state | description |
	// | --- | --- |
	// | `OK` | The CRUD operation or series of operations completed successfully. |
	// | `CREATING` | Creating of the environment instance is in progress. |
	// | `CREATION_FAILED` | The creation of the environment instance failed, and the environment instance was not created or was created but cannot be used. |
	// | `UPDATING` | Updating of the environment instance is in progress. |
	// | `UPDATE_FAILED` | The update of the environment instance failed, and  the environment instance was not updated. |
	// | `DELETING` | Deleting of the environment instance is in progress. |
	// | `DELETION_FAILED` | The deletion of the environment instance failed, and the environment instance was not deleted. |
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) The ID of the subaccount.
	// The ID of the subaccount.
	SubaccountID *string `json:"subaccountId,omitempty" tf:"subaccount_id,omitempty"`

	// (String) The ID of the tenant that owns the environment instance.
	// The ID of the tenant that owns the environment instance.
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`

	// (Attributes) (see below for nested schema)
	Timeouts *TimeoutsObservation `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// (String) The last provisioning operation on the environment instance. Possible values are:
	// The last provisioning operation on the environment instance. Possible values are:
	//
	// | type | description |
	// | --- | --- |
	// | `Provision` | The environment instance is created. |
	// | `Update` | The environment instance is changed. |
	// | `Deprovision` | The environment instance is deleted. |
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SubaccountEnvironmentInstanceParameters struct {

	// (String) The type of the environment instance that is used.
	// The type of the environment instance that is used.
	// +kubebuilder:validation:Optional
	EnvironmentType *string `json:"environmentType,omitempty" tf:"environment_type,omitempty"`

	// (String) The name of the landscape within the logged in region on which the environment instance is created.
	// The name of the landscape within the logged in region on which the environment instance is created.
	// +kubebuilder:validation:Optional
	LandscapeLabel *string `json:"landscapeLabel,omitempty" tf:"landscape_label,omitempty"`

	// (String) The name of the environment instance.
	// The name of the environment instance.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The configuration parameters for the environment instance.
	// The configuration parameters for the environment instance.
	// +kubebuilder:validation:Optional
	Parameters *string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (String) The name of the service plan for the environment instance in the corresponding service broker's catalog.
	// The name of the service plan for the environment instance in the corresponding service broker's catalog.
	// +kubebuilder:validation:Optional
	PlanName *string `json:"planName,omitempty" tf:"plan_name,omitempty"`

	// (String) The name of the service for the environment instance in the corresponding service broker's catalog.
	// The name of the service for the environment instance in the corresponding service broker's catalog.
	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// (String) The ID of the subaccount.
	// The ID of the subaccount.
	// +crossplane:generate:reference:type=github.com/sap/crossplane-provider-btp/apis/account/v1alpha1.Subaccount
	// +crossplane:generate:reference:extractor=github.com/sap/crossplane-provider-btp/apis/account/v1alpha1.SubaccountUuid()
	// +crossplane:generate:reference:refFieldName=SubaccountRef
	// +crossplane:generate:reference:selectorFieldName=SubaccountSelector
	// +kubebuilder:validation:Optional
	SubaccountID *string `json:"subaccountId,omitempty" tf:"subaccount_id,omitempty"`

	// Reference to a Subaccount in account to populate subaccountId.
	// +kubebuilder:validation:Optional
	SubaccountRef *v1.Reference `json:"subaccountRef,omitempty" tf:"-"`

	// Selector for a Subaccount in account to populate subaccountId.
	// +kubebuilder:validation:Optional
	SubaccountSelector *v1.Selector `json:"subaccountSelector,omitempty" tf:"-"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Timeouts *TimeoutsParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`
}

type TimeoutsInitParameters struct {

	// (String) Timeout for creating the environment instance.
	// Timeout for creating the environment instance.
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// (String) Timeout for deleting the environment instance.
	// Timeout for deleting the environment instance.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// (String) Timeout for updating the environment instance.
	// Timeout for updating the environment instance.
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type TimeoutsObservation struct {

	// (String) Timeout for creating the environment instance.
	// Timeout for creating the environment instance.
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// (String) Timeout for deleting the environment instance.
	// Timeout for deleting the environment instance.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// (String) Timeout for updating the environment instance.
	// Timeout for updating the environment instance.
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type TimeoutsParameters struct {

	// (String) Timeout for creating the environment instance.
	// Timeout for creating the environment instance.
	// +kubebuilder:validation:Optional
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// (String) Timeout for deleting the environment instance.
	// Timeout for deleting the environment instance.
	// +kubebuilder:validation:Optional
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// (String) Timeout for updating the environment instance.
	// Timeout for updating the environment instance.
	// +kubebuilder:validation:Optional
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

// SubaccountEnvironmentInstanceSpec defines the desired state of SubaccountEnvironmentInstance
type SubaccountEnvironmentInstanceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SubaccountEnvironmentInstanceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SubaccountEnvironmentInstanceInitParameters `json:"initProvider,omitempty"`
}

// SubaccountEnvironmentInstanceStatus defines the observed state of SubaccountEnvironmentInstance.
type SubaccountEnvironmentInstanceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SubaccountEnvironmentInstanceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SubaccountEnvironmentInstance is the Schema for the SubaccountEnvironmentInstances API. Creates an environment instance, such as a Cloud Foundry org, in a subaccount. Tips: You must be assigned to the admin role of the subaccount.Quota-based environments, such as Kyma, must first be assigned as entitlements to the subaccount. Further documentation: Cloud Foundry: https://help.sap.com/docs/btp/sap-business-technology-platform/org-management-using-sap-btp-command-line-interface-btp-cliKyma: https://help.sap.com/docs/btp/sap-business-technology-platform/available-plans-in-kyma-environmentConcept: https://help.sap.com/docs/btp/sap-business-technology-platform/environments
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,account}
type SubaccountEnvironmentInstance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.environmentType) || (has(self.initProvider) && has(self.initProvider.environmentType))",message="spec.forProvider.environmentType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parameters) || (has(self.initProvider) && has(self.initProvider.parameters))",message="spec.forProvider.parameters is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.planName) || (has(self.initProvider) && has(self.initProvider.planName))",message="spec.forProvider.planName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	Spec   SubaccountEnvironmentInstanceSpec   `json:"spec"`
	Status SubaccountEnvironmentInstanceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SubaccountEnvironmentInstanceList contains a list of SubaccountEnvironmentInstances
type SubaccountEnvironmentInstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SubaccountEnvironmentInstance `json:"items"`
}

// Repository type metadata.
var (
	SubaccountEnvironmentInstance_Kind             = "SubaccountEnvironmentInstance"
	SubaccountEnvironmentInstance_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SubaccountEnvironmentInstance_Kind}.String()
	SubaccountEnvironmentInstance_KindAPIVersion   = SubaccountEnvironmentInstance_Kind + "." + CRDGroupVersion.String()
	SubaccountEnvironmentInstance_GroupVersionKind = CRDGroupVersion.WithKind(SubaccountEnvironmentInstance_Kind)
)

func init() {
	SchemeBuilder.Register(&SubaccountEnvironmentInstance{}, &SubaccountEnvironmentInstanceList{})
}
